# Generated by Django 5.2.1 on 2025-05-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_fooditem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='id',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
