# Generated by Django 5.2.1 on 2025-05-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_remove_fooditem_id_alter_fooditem_image_fooditem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
