# Generated by Django 5.2.1 on 2025-05-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customeremailId',
            new_name='emailId',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerpassword',
            new_name='password',
        ),
    ]
