# Generated by Django 5.2.1 on 2025-05-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_foodbasket_basketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbasket',
            name='customer',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
        migrations.DeleteModel(
            name='FoodBasket',
        ),
    ]
